methodsWebsite="https://www.w3schools.com/python/python_ref_string.asp" #detaylı methods
message= "Hello There. My name is Faruk Akbulut"
# print(message)
# message= message.upper()
# print(message)
# message= message.lower()
# print(message)
# message= message.title()
# print(message)
# message= message.capitalize()
# print(message)
# message= message.strip()
# print(message)
# message= message.split()
# print(message)
# print(message[0])
# print(message[2])
# message= message.split('.')
# print(message)
# message= message.split()
# print(message)
# message=' '.join(message)
# print(message)
# message='---'.join(message)
# print(message)
# index=message.find('Faruk')
# print(index)
# index=message.find('Farukk')
# print(index) # kelime yok
# isFound= message.startswith('H')
# print(isFound)
# isFound= message.startswith('B')
# print(isFound)
# isFound= message.endswith('t')
# print(isFound)
# message=message.replace('Faruk','Mehmet Faruk')
# letter="Yıldırım gökyüzünde çaktı.\nYağmur çiselemeye başladı."
# letter=letter.replace('ı','i').replace('ö','o').replace('ü','u').replace('ç','c').replace('ğ','g').replace('ş','s')
# print(message)
# print(letter)
# message= message.center(50)
# print(message)
message= message.center(50,'*')
print(message)